---
- name: "Start Playbook: Install Nginx Proxy Server"
  hosts: all
  gather_facts: false
  become: true
  vars:
    nginx: /etc/nginx

  tasks:
    - name: Verify {{ nginx }} directory
      file:
        path: "{{ nginx }}"
        state: directory
    - name: Create Docker APT source list
      copy:
        dest: "{{ nginx }}/docker-compose.yaml"
        content: |
          version: '3.8'
          services:
            app:
              image: 'jc21/nginx-proxy-manager:latest'
              restart: unless-stopped
              ports:
                # These ports are in format <host-port>:<container-port>
                - '80:80' # Public HTTP Port
                - '443:443' # Public HTTPS Port
                - '81:81' # Admin Web Port
                # Add any other Stream port you want to expose
                # - '21:21' # FTP

              # Uncomment the next line if you uncomment anything in the section
              # environment:
                # Uncomment this if you want to change the location of
                # the SQLite DB file within the container
                # DB_SQLITE_FILE: "/data/database.sqlite"

                # Uncomment this if IPv6 is not enabled on your host
                # DISABLE_IPV6: 'true'

              volumes:
                - ./data:/data
                - ./letsencrypt:/etc/letsencrypt
    - name: Start docker compose service
      shell: cd {{ nginx }} && docker compose up -d
